### ISSUE TITLE
Don't activate CentOS Stream images

### ISSUE THREAD

**Issue by ondrejbudai** [RedHatInsights/image-builder-frontend#117]
Although I think that it's possible to subscribe a non-RHEL image, it doesn't make much sense for the majority of use-cases.

I propose to hide the activation step when CentOS Stream is selected.

**Comment by teg** [comment]
I'm curious what would happen. would it work with insights? Might be worth it, depending on the experience...

**Comment by ondrejbudai** [comment]
Nope, centos doesn't ship `insights-client`, I had to manually remove it from the list of packages in osbuild-composer: https://github.com/osbuild/osbuild-composer/blob/d7b0323a2dec205b7a41bd9b4c5d7e30982fc44f/internal/distro/rhel84/distro.go#L196

**Comment by jkozol** [comment]
Closed by #227
