### ISSUE TITLE
When you share an AWS image the status is not refreshed automatically

### ISSUE THREAD

**Issue by jrusz** [RedHatInsights/image-builder-frontend#1177]
When you share an AWS image the status of the clone is always pending, you have to refresh the page to actually check if it's done. This is potentially confusing to the user as the regular image builds refresh the status automatically just fine so it would be reasonable to assume it's the same for the clone.

![image](https://github.com/RedHatInsights/image-builder-frontend/assets/55534579/d7a71303-4ca3-4d7f-830b-a4f75fd87d87)

**Comment by lucasgarfield** [comment]
Resolved by #1320.
