### ISSUE TITLE
[RFE] Provide AMI id for newly uploaded images

### ISSUE THREAD

**Issue by apitanga** [RedHatInsights/image-builder-frontend#118]
Once a new image is created and uploaded to EC2 it is difficult to identify the image and thus to locate it in one's EC2 console.

A UUID is provided but it's not clear what that UUID refers to.

Please provide the AMI id of the newly uploaded image so operators can easily find the image in the EC2 portal.

![Screenshot from 2021-03-12 13-37-33](https://user-images.githubusercontent.com/752722/110985278-455d0d00-833a-11eb-977b-f0bd507bbb4b.png)

**Comment by teg** [comment]
The images list is due for an overhaul, and in particular to give AMI id's and/or links to the images. The API exposes it, we just need to update the UI too.

**Comment by jkozol** [comment]
Closed in favor of #134
