### ISSUE TITLE
Add All/Selected toggle on the custom repositories step #

### ISSUE THREAD

**Issue by croissanne** [RedHatInsights/image-builder-frontend#1201]
Easily view the repositories that are currently selected while clicking through the pages of repos.

**Comment by regexowl** [comment]
Adding [mocks](https://www.sketch.com/s/ac25729e-df9b-4e74-a09c-badb62787d24/a/27PobYe) with the All/Selected toggle 

![Screenshot from 2023-11-02 16-29-28](https://github.com/RedHatInsights/image-builder-frontend/assets/49452678/a2dd0971-6766-4cb8-9f12-7eb24b0ccd28)

**Comment by lucasgarfield** [comment]
This had been blocked because the modal didn't have enough space, now with the full page wizard we can do this. Could be good for @mgold1234 to look at.
