### ISSUE TITLE
Oscap support - ImageWizard

### ISSUE THREAD

**Issue by kingsleyzissou** [RedHatInsights/image-builder-frontend#1248]
We'd like to add support for creating openscap hardened images in the consoledot frontend.

Currently there is only 1 configuration option for the openscap settings. The user will need to select a profile id that will then be used to harden and remediate a image. We would most likely need to get the list of profiles from the compliance service in consoledot.

Additionally, each profile has its own mountpoint/filesystem configuration settings - we might be able to get this information from the compliance service. But the first step would be to get a step for openscap in the wizard and to be able to select a profile.

**Comment by regexowl** [comment]
Functionality added in https://github.com/RedHatInsights/image-builder-frontend/pull/1371
