### ISSUE TITLE
Wizard: document what registraiton does

### ISSUE THREAD

**Issue by teg** [RedHatInsights/image-builder-frontend#126]
Currently this subscribes the image and registeres with insights. Down tho road we want insights registration to be opt-out, but either way we should make sure to explain what registration means.

**Comment by katierik** [comment]
I'd like to suggest that we use RHC (Red Hat connector) for registration. RHC registers with subscriptions, and with Insights, and allows the user to configure those connection options through a dashboard inside console dot.

https://access.redhat.com/documentation/en-us/red_hat_insights/2021/html-single/red_hat_connector_configuration_guide/index

**Comment by teg** [comment]
> I'd like to suggest that we use RHC (Red Hat connector) for registration. RHC registers with subscriptions, and with Insights, and allows the user to configure those connection options through a dashboard inside console dot.
> 
> https://access.redhat.com/documentation/en-us/red_hat_insights/2021/html-single/red_hat_connector_configuration_guide/index

Totally agree, this would be great!
