### ISSUE TITLE
RFE: Remove Search tags widget from top of screen

### ISSUE THREAD

**Issue by atodorov** [RedHatInsights/image-builder-frontend#13]
We've talked about this last week but opening an issue so it's not forgotten. I'm talking about this:
![image_builder_search_tags](https://user-images.githubusercontent.com/1002300/95739614-c6cd4800-0c93-11eb-9ecc-f54ab9d0a5cb.png)

which doesn't seem to be part of Image Builder and is confusing.

**Comment by teg** [comment]
I came here to open the same issue. I asked Katie about this, and apparently insights does not currently allow this to be removed, only disabled (as it is now). I think we should request that possibility.

**Comment by jkozol** [comment]
After discussing this again this is not anything we can control from image builder frontend and is enabled for all clouddot applications. They have no intention of removing it at this time so I am closing this issue since it can not be fixed by us and we have no further steps to take.
