### ISSUE TITLE
AWS AMI field is seemingly trying to load value while image is still building

### ISSUE THREAD

**Issue by jrusz** [RedHatInsights/image-builder-frontend#1362]
This does not seem to cause any issues however it doesn't look good and gives off a feeling that something is not working right. There is this grey flowing gradient in the filed where AMI is going to appear once image is done building. In the past it was just empty while the image was building.

![image](https://github.com/RedHatInsights/image-builder-frontend/assets/55534579/dc263f69-18ca-411a-8ead-d78cbfede8be)

**Comment by regexowl** [comment]
Fixed by https://github.com/RedHatInsights/image-builder-frontend/pull/1518
