### ISSUE TITLE
Building CentOS Stream 8 image doesn't seem to finish

### ISSUE THREAD

**Issue by atodorov** [RedHatInsights/image-builder-frontend#138]
I've selected a CentOS Stream 8 content and AWS upload target. I've selected "bash" as the RPM package which I want inside the image. I get "Image build in progress" for around 30 minutes and the process seems to be stuck.

**Comment by jkozol** [comment]
@atodorov Can you confirm that CentOS Stream images still fail to build for you?

**Comment by jkozol** [comment]
Closing since I successfully built an image in production.
