### ISSUE TITLE
Deduplication of OpenSCAP Mountpoints

### ISSUE THREAD

**Issue by kingsleyzissou** [RedHatInsights/image-builder-frontend#1385]
It looks like the deduplication of OpenSCAP mount points might be a little too aggressive. For reference I chose the `cis` profile.

Expected:
- /home
- /tmp
- /var
- /var/log
- /var/log/audit
- /var/tmp

Actual:
- /home
- /tmp
- /var

![image](https://github.com/RedHatInsights/image-builder-frontend/assets/20438192/09446f5e-248d-4d4c-8294-e3705541adf8)

**Comment by lavocatt** [comment]
Good catch, thanks!! I'll fix it tomorrow
