### ISSUE TITLE
CreateImageWizard: Selected packages should be filtered out of the available options column

### ISSUE THREAD

**Issue by Gundersanne** [RedHatInsights/image-builder-frontend#189]
https://marvelapp.com/prototype/6g7dja9/screen/76420982

**Comment by Gundersanne** [comment]
![image](https://user-images.githubusercontent.com/11140201/118520759-9f16f480-b73a-11eb-92e8-1661d6205c11.png)

**Comment by jkozol** [comment]
This is fixed
