### ISSUE TITLE
ImagesTable: Fix uneven spacing of Create Image button

### ISSUE THREAD

**Issue by Gundersanne** [RedHatInsights/image-builder-frontend#192]
![image](https://user-images.githubusercontent.com/11140201/118519843-c4efc980-b739-11eb-9759-f1620bb23ade.png)

**Comment by ochosi** [comment]
This seems to be fixed one way or another..?
![image](https://user-images.githubusercontent.com/261436/129593599-c01d7900-ab6a-416c-8c9c-37db79a4a88f.png)
