### ISSUE TITLE
[BZ#1974790][RFE] Suggestion to add a name to headless column

### ISSUE THREAD

**Issue by yuxisun1217** [RedHatInsights/image-builder-frontend#244]
Bugzilla issue: https://bugzilla.redhat.com/show_bug.cgi?id=1974790

Description of problem: Column head name is not available.

Suggestion for adding a head to the headless column and thus clarify to users about the instances.
Possible head name suggestions: Instances, Instance options, Uploaded Instances. 

How reproducible: Always

Steps to Reproduce:
1. Access Image Builder at cloud.redhat.com
2. Initial page load the "Created Images".
3. There is one column with no name.

![Screenshot from 2021-06-22 16-21-23](https://user-images.githubusercontent.com/19280786/123024096-1eb77380-d40b-11eb-92b2-474aa0002815.png)

**Comment by jkozol** [comment]
@katierik thoughts on this?

**Comment by katierik** [comment]
"Instance" as a col header is 👍
