### ISSUE TITLE
Feature tour step 3 exeeds screen height

### ISSUE THREAD

**Issue by rgolangh** [RedHatInsights/image-builder-frontend#445]
The feature tour on step 3 exceeds the screen height and so the buttons are unreachable. Zooming out is a workaround
Firefox 94, Fedora 35
![image](https://user-images.githubusercontent.com/4987932/142603876-70a293b2-17ed-4e3b-ab4f-042d7be82de6.png)

**Comment by jkozol** [comment]
Thanks for bringing this to our attention. This is going to be a downstream fix and is not controlled by image-builder-frontend. I will leave this issue up until it is addressed by the pendo team but no changes can be made to the image-builder-frontend to fix this.

**Comment by jkozol** [comment]
This has now been fixed
