### ISSUE TITLE
packages "add all" button doesn't work

### ISSUE THREAD

**Issue by Gundersanne** [RedHatInsights/image-builder-frontend#447]
the double arrow `»` which adds all packages from the left hand column doesn't work, 0 packages chosen on the review screen.

**Comment by teg** [comment]
Did you work on this @kingsleyzissou, or did I misremember?

**Comment by kingsleyzissou** [comment]
I did the package ordering. I think Jacob may have fixed this when he refactored this component

**Comment by jkozol** [comment]
@Gundersanne can I get a double check on this issue? I am unable to replicate it. It had been broken but with this weeks release it should be working on production.

**Comment by Gundersanne** [comment]
Hm double checked. So what I exactly did on stage:

Use add all to add whatever is listed under vim
![image](https://user-images.githubusercontent.com/11140201/142744173-e910d9f7-2993-48ea-83a1-46bb12a60faf.png)

The # of chosen packages is listed as 0:
![image](https://user-images.githubusercontent.com/11140201/142744170-e3279812-45d2-40aa-b2a3-e7c94df90a05.png)

Request payload:

```
{
  "distribution": "rhel-85",
  "image_requests": [
    {
      "architecture": "x86_64",
      "image_type": "ami",
      "upload_request": {
        "type": "aws",
        "options": {
          "share_with_accounts": [
            "012345678912"
          ]
        }
      }
    }
  ],
  "customizations": {
    "packages": []
  }
}
```

**Comment by jkozol** [comment]
Ahh yes I see this now. Working on a fix :)
