### ISSUE TITLE
CreateImageWizard: validate input for azure resource group

### ISSUE THREAD

**Issue by Gundersanne** [RedHatInsights/image-builder-frontend#488]
The validation pattern  MS uses is `^[-\p{L}\._\(\)\w]+$` ; let's use that as well?

**Comment by jkozol** [comment]
Per this page: https://docs.microsoft.com/en-us/rest/api/resources/resource-groups/create-or-update I will use: `^[-\w._()]+$` instead. `\p{}` for unicode matching isn't supported by all browsers and versions of ecma scrpt so I will leave it out.
