### ISSUE TITLE
Header popover close button doesn't align

### ISSUE THREAD

**Issue by jkozol** [RedHatInsights/image-builder-frontend#593]
This might be a patternfly issue. The X doesn’t line up with the end of the content popover.

![image9](https://user-images.githubusercontent.com/11712857/155201264-ea020eef-d564-4c17-a1a8-aa708152136c.png)

**Comment by Gundersanne** [comment]
So this is definitely a patternfly thing https://www.patternfly.org/v4/components/popover all the examples have the same alignment. Could open an issue with in https://github.com/patternfly/patternfly-design for it.

**Comment by chloenayon** [comment]
To be addressed: https://github.com/patternfly/patternfly/issues/4781

**Comment by regexowl** [comment]
Fixed by PatternFly
