### ISSUE TITLE
Include selected activation key info

### ISSUE THREAD

**Issue by jkozol** [RedHatInsights/image-builder-frontend#603]
Add the available RHEL 9+ features to the activation keys step per the mocks:  https://marvelapp.com/prototype/6g7dja9/screen/76602546

**Comment by regexowl** [comment]
The activation key information was added in https://github.com/RedHatInsights/image-builder-frontend/pull/886 and the Registration step was updated by https://github.com/RedHatInsights/image-builder-frontend/pull/968
