### ISSUE TITLE
Activation key needs validation

### ISSUE THREAD

**Issue by jkozol** [RedHatInsights/image-builder-frontend#624]
The user should not be able to continue with no activation key selected.

**Comment by benblasco** [comment]
To be more specific, leaving the AK name blank will result in an unhelpful error message upon clicking the "Create Image" button as per the screenshot below.  The error is "Status 400: Bad Request", which doesn't tell me that I accidentally left the AK field blank.

![image](https://user-images.githubusercontent.com/42140583/157022544-af0c49b5-d3dd-4a28-92c7-ee42c31eab2f.png)
