### ISSUE TITLE
Image output validation bug

### ISSUE THREAD

**Issue by Gundersanne** [RedHatInsights/image-builder-frontend#683]
Selecting and de-selecting target environment will allow you to continue, even though you might not have any targets selected.

https://user-images.githubusercontent.com/11140201/161585899-58dc4efb-2e4e-4413-8b00-e1b1fd1d2bcd.mp4

**Comment by jkozol** [comment]
@Gundersanne this was actually just fixed by #669. Are you still experiencing this on main?

**Comment by Gundersanne** [comment]
Ah woops! This got fixed. Sorry for the noise.
