### ISSUE TITLE
Wizard: Review step updates

### ISSUE THREAD

**Issue by lucasgarfield** [RedHatInsights/image-builder-frontend#774]
Update the Review step to match the updated mocks: https://marvelapp.com/prototype/6g7dja9/screen/82042200

**Comment by regexowl** [comment]
Going through the issue I have two questions regarding the mockups:
- Do we want to changes the "Google account" to "Account email" in Target environments under Google Cloud Platform? The change would affect the `Target environment -> Google Cloud Platform` step as well as the Google account type is read from there.
- Is it possible to read value of the Volume group needed for the `Partitions` popover anywhere? Looking at the api, it seems the only two values under Filesystem are `min_size` and `mountpoint`

**Comment by croissanne** [comment]
> @lucasgarfield @croissanne Going through the issue I have two questions regarding the mockups:
> 
>     * Do we want to changes the "Google account" to "Account email" in Target environments under Google Cloud Platform? The change would affect the `Target environment -> Google Cloud Platform` step as well as the Google account type is read from there.

No strong opinion, but it might just have been an oversight? @arburka was this change intentional?

> 
>     * Is it possible to read value of the Volume group needed for the `Partitions` popover anywhere? Looking at the api, it seems the only two values under Filesystem are `min_size` and `mountpoint`

Setting options on volume groups are currently not supported by composer (nor is swap for that matter). As soon as users specify custom mountpoints, we'll create a single volume group with all the partitions attached to that group.

**Comment by regexowl** [comment]
@croissanne 
> Setting options on volume groups are currently not supported by composer (nor is swap for that matter). As soon as users specify custom mountpoints, we'll create a single volume group with all the partitions attached to that group.

![Screenshot from 2022-11-03 10-30-58](https://user-images.githubusercontent.com/49452678/199687386-e2b91d0a-4845-42e9-8f73-e2b4eafc375c.png)

I see, would we want to add the column with some default value as seen in the mock or don't add it?

**Comment by croissanne** [comment]
> 
> I see, would we want to add the column with some default value as seen in the mock or don't add it?

I wouldn't add it until we actually support customizing it.
