### ISSUE TITLE
Wizard: Image output step links

### ISSUE THREAD

**Issue by lucasgarfield** [RedHatInsights/image-builder-frontend#776]
The first link links to the RHEL 8 docs - should it be updated?

Should the second link be specific to target environments?

Need to confirm URLs with @katierik

Current:
![image](https://user-images.githubusercontent.com/95542540/185187510-e32217b4-c4e3-4f22-92bf-3d945c7ba41e.png)

**Comment by katierik** [comment]
RHEL 9 docs should suffice: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/composing_a_customized_rhel_system_image/creating-system-images-with-composer-web-console-interface_composing-a-customized-rhel-system-image#accessing-composer-gui-in-the-rhel-8-web-console_creating-system-images-with-composer-web-console-interface

**Comment by adithyaakrishna** [comment]
@lucasgarfield @katierik Is this issue still valid? If so, would like to take it up :)

**Comment by croissanne** [comment]
Reverted in https://github.com/RedHatInsights/image-builder-frontend/pull/869
