### ISSUE TITLE
Wizard: System configuration updates

### ISSUE THREAD

**Issue by lucasgarfield** [RedHatInsights/image-builder-frontend#778]
We need to update the System configuration step to match the new mocks: https://marvelapp.com/prototype/6g7dja9/screen/81325308 

A few specific issues to take care of:

1. Misalignment issue: 
![image](https://user-images.githubusercontent.com/95542540/185195396-c07a823a-a414-42f5-89f2-eeb47b8f2da4.png)

2. When adding new mount points by clicking `+ Add partition`, the first new partition will be `/home`, and then the second new partition will _also_ be `home`... which immediately shows an error. As per the updated mocks, validation will now be done upon clicking `Next`.
![image](https://user-images.githubusercontent.com/95542540/185195499-4f360179-3902-4033-bbd0-dbb3ba476b27.png)

**Comment by kingsleyzissou** [comment]
This was fixed with #788
