### ISSUE TITLE
ImagesTable: Don't show image discovery url in case the build failed

### ISSUE THREAD

**Issue by croissanne** [RedHatInsights/image-builder-frontend#779]
![image](https://user-images.githubusercontent.com/11140201/185578080-841cc5e9-7c6d-48da-acfe-66bb3518f70b.png)

There's no image if the build is failed, so showing the launch instance url etc... doesn't make any sense.

**Comment by arburka** [comment]
Can you retry the image, or do you have to rebuild it?

I agree that it should not be active, I'm wondering if its a better option to disable instead of removing the action.

**Comment by arburka** [comment]
This looks like it was fixed.
<img width="1291" alt="Screen Shot 2022-09-13 at 11 00 34 PM" src="https://user-images.githubusercontent.com/88330245/190049175-2c3fd175-3162-42fb-a309-a93496487868.png">

**Comment by lavocatt** [comment]
Fixed by: https://github.com/RedHatInsights/image-builder-frontend/commit/357401ecfa76783f7f32bc2b2a31ec8308086a73
