### ISSUE TITLE
Remove the Download Icon

### ISSUE THREAD

**Issue by arburka** [RedHatInsights/image-builder-frontend#803]
<img width="603" alt="Screen Shot 2022-09-13 at 10 32 41 PM" src="https://user-images.githubusercontent.com/88330245/190045472-54af8d60-0a18-417f-991a-d26217915333.png">

The download icon was kept on the right-hand side to be consistent with the launch instance icon, but it's an incorrect pattern and will have to be repeated every time we introduce a new primary action.

Most icons associated with actions should be on the left, and the download should too!

**Comment by arburka** [comment]
Also if the icons aren't "small" can we make them "small" instead of "medium?"

**Comment by arburka** [comment]
It is [uncommon](https://www.patternfly.org/v4/components/table/design-guidelines) for use to use icons in addition to the "action links." This is a "slippery slope" issue because, while the download has an obvious and easily understood icon, many actions may be more obscure thus icon will have no meaning (just clutter), OR we have to make an active choice to introduce inconsistency to our application by only adding the icon when we have one available.

The UX team responsible for HMS has agreed not to recommend icons in this situation in any of our work.

**Comment by Gundersanne** [comment]
![image](https://user-images.githubusercontent.com/11140201/191060123-d01bb7e1-2142-4609-b017-ad4b7ee69ee9.png)

Should we put the extension in brackets?

**Comment by arburka** [comment]
I think it would help. It would also help to differentiate this download from the others one. However, I hope to learn more about what the action needs to say through user feedback.

Download image (.qcow)
Download compose request (.json)
