### ISSUE TITLE
ImagesTable: Don't show 'Launch instance' when build failed

### ISSUE THREAD

**Issue by ochosi** [RedHatInsights/image-builder-frontend#832]
Currently we allow this combination to appear in the ImagesTable (see screenshot).
I can't come up with a scenario where this would make sense as it'd not be possible to launch (or download?) a failed build.

![image](https://user-images.githubusercontent.com/261436/196151454-0831d6eb-bcb5-41b9-93b4-47488f54e171.png)

**Comment by lavocatt** [comment]
Fixed by: #357
