### ISSUE TITLE
Images table target and instance columns broken for aws.s3 type images

### ISSUE THREAD

**Issue by lucasgarfield** [RedHatInsights/image-builder-frontend#838]
![image](https://user-images.githubusercontent.com/95542540/197174955-64400efd-2a99-42b2-bad3-2dd93c45e9c4.png)

**Comment by lucasgarfield** [comment]
This is occurring for edge image types, which are currently not supported by the Wizard. Since they are supported by the API and may appear in the table, perhaps we should update the table to display their information correctly.

**Comment by croissanne** [comment]
We should either not show them at all or merge https://github.com/RedHatInsights/image-builder-frontend/pull/722

**Comment by jkozol** [comment]
I think we should show them. I'll updated #722. Totally forgot about it haha.

**Comment by regexowl** [comment]
Fixed by https://github.com/RedHatInsights/image-builder-frontend/pull/722
