### ISSUE TITLE
Clearing the release select doesn't seem to clear the selection and is confusing

### ISSUE THREAD

**Issue by jrusz** [RedHatInsights/image-builder-frontend#893]
In the "Create Image modal" in the first step where the "Release" can be selected there is one option already pre-selected. There is a "clear button" next to it which when clicked doesn't seem to actually clear the selection as it's still shown but prevents clicking on "Next" and also the "Registration" step is hidden.
![image](https://user-images.githubusercontent.com/55534579/210325207-85995d75-d81b-4609-bb57-1b28d931cec9.png)

And after clicking the clear button it looks like this:
![image](https://user-images.githubusercontent.com/55534579/210325291-4b5782a2-0cde-486f-ba72-64007e611204.png)

So the Release still seems to be selected but I am unable to continue which seems confusing. Maybe it would make sense to hide the "clear button"? Or at least somehow show that nothing is selected there once cleared.

**Comment by lucasgarfield** [comment]
Nice bug find on the validation. I think you're right about just removing it, and looking at the Patternfly examples there is good precedent for doing so.
