### ISSUE TITLE
chrome.init is deprecated

### ISSUE THREAD

**Issue by lucasgarfield** [RedHatInsights/image-builder-frontend#906]
New console warning after merging 772aca36fa6cacf96ed92472ce4cd33d290395d8: `Calling deprecated "chrome.init function"! Please remove the function call from your code. Functions "on" and "updateDocumentTitle" are directly accessible from "useChrome" hook. `

**Comment by regexowl** [comment]
Fixed by https://github.com/RedHatInsights/image-builder-frontend/pull/1069
