### ISSUE TITLE
Add information to automatic configuration step.

### ISSUE THREAD

**Issue by arburka** [RedHatInsights/image-builder-frontend#911]
Add additional information to the file system configuration when selecting the "automatic" option. 
<img width="719" alt="Screen Shot 2023-01-09 at 2 53 33 PM" src="https://user-images.githubusercontent.com/88330245/211396386-c4b1243a-351c-4ecb-99f4-1c10728a05fe.png">

**Comment by regexowl** [comment]
@arburka @croissanne Where should the `Learn more` link lead to? And for the manual configuration there's a link called `Partition naming schemes and mount points`, could you let me know the url for that as well? I was trying to look around the mocks, but was unable to find that information.
