### ISSUE TITLE
Images table - does it need a max width?

### ISSUE THREAD

**Issue by lucasgarfield** [RedHatInsights/image-builder-frontend#933]
On widescreen monitors the Images Table looks s t r e t c h e d out.

Any thoughts @arburka?

![image](https://user-images.githubusercontent.com/95542540/212674477-4370a9e3-e70e-4853-a1fb-dc983ee20267.png)

**Comment by mmenestr** [comment]
Communicated this to @arburka but also wanted to write it here. 

It's true that we should probably set a limit as to how wide a table can get. Currently, there is no max width on a table, but  page sections have [support for width limit](https://www.patternfly.org/v4/components/page/#pagesection). What the "isWidthLimited" prop does is make the whole page (except for things like the masthead) get restricted to ~2000px width, I believe.

So you can’t apply a max width to a table, but you can put a table inside of that element, which would give you the same end result!
