### ISSUE TITLE
Images table - release values are not consistent

### ISSUE THREAD

**Issue by jrusz** [RedHatInsights/image-builder-frontend#946]
There is a difference between the value in the "Release" column based on whether the image is built via api or ui. See the following screenshot
![image](https://user-images.githubusercontent.com/55534579/214835744-4d5b07c7-7c72-4ee5-99fa-6926590c3c0d.png)

The capital `RHEL 9` is from UI and the `rhel-9` is from api. I suppose this should be the same regardless the way the image is built?

**Comment by mgold1234** [comment]
fixed in that pr https://github.com/RedHatInsights/image-builder-frontend/pull/1185
